// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALju1Qh0J-NF50JCQ6omWEVorUgJsZR7Y',
    appId: '1:167944220965:web:7d97a056f5e7f2f9a56acc',
    messagingSenderId: '167944220965',
    projectId: 'x-twitter-clone-d013a',
    authDomain: 'x-twitter-clone-d013a.firebaseapp.com',
    storageBucket: 'x-twitter-clone-d013a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnoKFJ5z3iRxJU_yjCkqHSx7k7vvoEXl8',
    appId: '1:167944220965:android:802624cb0a1a7cb3a56acc',
    messagingSenderId: '167944220965',
    projectId: 'x-twitter-clone-d013a',
    storageBucket: 'x-twitter-clone-d013a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbTwsYo__CMGixGZEou612FvC5yosja9M',
    appId: '1:167944220965:ios:e315122e1901eb78a56acc',
    messagingSenderId: '167944220965',
    projectId: 'x-twitter-clone-d013a',
    storageBucket: 'x-twitter-clone-d013a.firebasestorage.app',
    iosBundleId: 'com.example.flutterXClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbTwsYo__CMGixGZEou612FvC5yosja9M',
    appId: '1:167944220965:ios:e315122e1901eb78a56acc',
    messagingSenderId: '167944220965',
    projectId: 'x-twitter-clone-d013a',
    storageBucket: 'x-twitter-clone-d013a.firebasestorage.app',
    iosBundleId: 'com.example.flutterXClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALju1Qh0J-NF50JCQ6omWEVorUgJsZR7Y',
    appId: '1:167944220965:web:8029285e59777a2ca56acc',
    messagingSenderId: '167944220965',
    projectId: 'x-twitter-clone-d013a',
    authDomain: 'x-twitter-clone-d013a.firebaseapp.com',
    storageBucket: 'x-twitter-clone-d013a.firebasestorage.app',
  );
}
